apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopcloud-gateway
spec:
  replicas: 3  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: hopcloud-gateway
  template:
    metadata:
      labels:
        app: hopcloud-gateway
    spec:
      containers:
        - name: hopcloud-gateway
          image: hopcloud-gateway/v1.0.0
          ports:
            - containerPort: 8080
