apiVersion: v1
kind: Service
metadata:
  name: hopcloud-service
spec:
  selector:
    app: hopcloud-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Use "LoadBalancer" if your Kubernetes cluster supports it
